### ISSUE TITLE
The new export syntax breaks bundlers for libraries that use callbag-interval

### ISSUE THREAD

**Issue by Risto-Stevcev** [staltz/callbag-interval#7]
Version 1.0.0 of this library was using `module.exports = interval` to export the function as a default, but the new 1.1.0 version is using `export default interval`, which is causing problems for libraries that depend on `callbag-interval` and need to work on both nodejs and the browser.

## Steps to Reproduce

Files
```
package.json
src/
  index.js
example-parcel.html
example-webpack.html
webpack.conf.js
```

Dependencies
```sh
$ yarn add callbag-interval callbag-for-each
$ yarn add --dev webpack webpack-cli parcel-bundler
```

_src/index.js_
```js
const interval = require('callbag-interval')
const forEach = require('callbag-for-each')
forEach(console.log)(interval(1000))
```

_webpack.conf.js_
```js
const path = require('path');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  devtool: 'inline-source-map',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist')
  }
};
```

_example-webpack.html_
```html
<html>
  <head><script src="./dist/main.js"></script></head>
  <body></body>
</html>
```

_example-parcel.html_
```html
<html>
  <head><script src="./src/index.js"></script></head>
  <body></body>
</html>
```

Works for node:
```sh 
$ node src/index.js 
0
1
2
3
^C
```
But fails for the bundles:

```sh
$ ./node_modules/.bin/parcel example-parcel.html
```
`http://localhost:1234`

and
```sh
$ ./node_modules/.bin/webpack-cli
$ http-server .
```
`http://localhost:8080/example-webpack.html`

Both error out with
```js
TypeError: interval is not a function
```

## Result

Bundlers like parcel and webpack think this file is an es6 module, so it will actually end up transpiling it to something like `{default: interval}`. But since this code is importing callbag-interval is using `require`, it thinks it's a commonjs module and bundle errors out with `interval is no a function`. So I can use the above library with nodejs but not the browser.

If I update `index.js` to use es6 import sytnax I just end up with the same problem in reverse: it will work with the bundles, but then I can't use the library with nodejs. 

The old `module.exports` syntax worked with both, and I think it should be switched back to the old `module.exports` syntax since it's consistent with all other callbag libraries and it's also the most reliable right now.

**Comment by staltz** [comment]
Hi! If that's true, that's a mistake, I'm sorry for the breaking change. But I think it should still work. `index.js` is being compiled to `index.cjs.js` at npm publish time, and in package.json, the `"main"` field is defined as `index.cjs.js` so it should still work. Not sure how it ended up not working in node.js for you. Check the `test.js` file in this repo, and see how we're importing `interval`.

**Comment by Risto-Stevcev** [comment]
No it works with nodejs but breaks the bundles. I wrote a wrapper library for Ocaml that depends on this library ([bs-callbag-interval](https://github.com/Risto-Stevcev/bs-callbag-interval)) and I want it to be usable on both nodejs and the browser. The latest 1.1.0 breaks things so you can't do that. I updated the ticket with details to reproduce the issue so you can see what I mean

**Comment by Risto-Stevcev** [comment]
See also: Microsoft/TypeScript#2719

**Comment by loreanvictor** [comment]
@staltz any news on this?

**Comment by staltz** [comment]
> The old module.exports syntax worked with both, and I think it should be switched back to the old module.exports syntax since it's consistent with all other callbag libraries and it's also the most reliable right now.

Actually all other callbag libraries (that I author) use the same pattern, and also other libraries such as [cyclejs/callbags](https://github.com/cyclejs/callbags/blob/master/package.json) also use this pattern.

I think the issue here is that **when using bundlers** the imports are wrong, they should be `import interval from 'callbag-interval'`, not `const interval = require('callbag-interval')`, because bundlers like Webpack anyway change `require`'s implementation and semantics.

Closing because this doesn't seem an issue in this library.

**Comment by loreanvictor** [comment]
> Actually all other callbag libraries (that I author) use the same pattern

Do they? I am not 100% certain how this should be or are these differences meaningful or not, but for example there is definitely a difference in [how `callbag-pipe` does it](https://github.com/staltz/callbag-pipe/blob/a2e5b985ce7aa55de2749e1c3e08867f45edc6fa/readme.js#L116) vs how [`callbag-interval` does it](https://github.com/staltz/callbag-interval/blob/dcd3155526fc7ffbb14ad9b6c27ce49186b1ae8c/index.js#L12) (the other difference being `callbag-pipe` does not use any bundler as well).

It really seems to be a difference in `callbag-interval`, and [it does break even with `import interval from 'callbag-interval';` syntax](https://stackblitz.com/edit/callbag-interval-import-issue?file=index.ts).

**Comment by staltz** [comment]
callbag-pipe is lagging behind the others, it just needs to be updated. See e.g. callbag-merge.

Your Stackblitz example works correctly in the JS runtime. It's types that seem to be weird.

**Comment by loreanvictor** [comment]
yes, I just wanted to highlight that even in relatively standardized environments this issue persists (and the error causes more strict typescript transpilation to result in error).

**Comment by Risto-Stevcev** [comment]
I don't think I made this clear enough when I wrote it:
The issue is that before the minor version bump, I could use commonjs syntax to import this library, and it would work in both bundlers and nodejs.
But now if you want to use it for bundlers then you need to use es6 import syntax, and if you want to use it with nodejs directly you use commonjs syntax. The problem with this is that I can't write a proper wrapper library for ReasonML because the compiler config is controlled by the library author. So if you want to use it in ReasonML on both the frontend and backend then you're sort of out of luck. You could use the experimental es6 support in nodejs, but in my experience it's been a huge headache and doesn't work very well
