### ISSUE TITLE
Typing issue on v@1.1.0

### ISSUE THREAD

**Issue by loreanvictor** [staltz/callbag-interval#8]
Follow up on [this](https://github.com/staltz/callbag-interval/issues/7#issuecomment-712108149), I took a look at the issue with the typings. There is a mis-match between contents of [`types.d.ts` on master](https://github.com/staltz/callbag-interval/blob/master/types.d.ts), and [`types.d.ts` on latest published package](https://unpkg.com/callbag-interval@1.1.0/types.d.ts) (which is now `1.1.0`). The typing issue mentioned in the linked comment is due to this, since in the published version there is no default export declared (while in the master version there is).

So I suspect just publishing again with the correct `types.d.ts` (which is on master) should fix the typing issues.

Edit: for convenience, this is `types.d.ts` on master:
```ts
import { Source } from 'callbag';
declare const interval: (period: number) => Source<number>;
export default interval
```
And this is `types.d.ts` published on v@1.1.0:
```ts
import { Source } from 'callbag';
export declare const interval: (period: number) => Source<number>;
```

**Comment by staltz** [comment]
released 1.2.0
